export const SAVE_AIRPORT_TO_STORE = 'SAVE_AIRPORT_TO_STORE';
export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';
export const LOADING_ERROR = 'LOADING_ERROR';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SEND_AIRPORT_DETAIl = 'SEND_AIRPORT_DETAIl';

